stages:
 - test
 - scan
 - docker

variables:
  SONAR_SCANNER_VERSION: 5.0.1.3006
  GIT_DEPTH: "0"

test_job:
  stage: test
  tags:
    - linux
  script:
    - sudo apt-get update
    - sudo rm -rf /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/debconf/*.dat /var/cache/apt/archives/lock
    - sudo dpkg --configure -a
    - sudo apt-get install -f
    - sudo apt-get install -y python3-dev python3-pip libasound2-dev
    - pip install -r requirements.txt
    - pip install coverage
    - cd localstack_ui
    - ~/.local/bin/coverage run -m unittest app_unittest.py
    - ~/.local/bin/coverage xml
    - rm -rf __pycache__
  artifacts:
    paths:
      - localstack_ui/coverage.xml
  variables:
    GIT_STRATEGY: clone

scan_job:
  stage: scan
  tags:
    - linux
  script:
    - sudo apt-get update
    - sudo rm -rf /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/debconf/*.dat /var/cache/apt/archives/lock
    - sudo dpkg --configure -a
    - sudo apt-get install -f
    - sudo apt-get install -y unzip openjdk-17-jre npm
    - pushd ~
    - curl -o /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip
    - unzip -n /tmp/sonar-scanner.zip
    - popd
    - cd localstack_ui
    - export SONAR_TOKEN=$(echo -n "c3FhXzk5Njc0NmRhMGZiYWNmNTc4ZWNhNTg5NWZmZmM3YWUwMjY3ZGM1ZjkK"|base64 --decode) && ~/sonar-scanner-${SONAR_SCANNER_VERSION}/bin/sonar-scanner -Dsonar.token=$SONAR_TOKEN
  dependencies:
    - test_job
  artifacts:
    paths:
      - localstack_ui/coverage.xml
  variables:
    GIT_STRATEGY: clone

docker_job:
  stage: docker
  tags:
    - linux
  script:
    - sudo apt update
    - sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt update
    - sudo apt install -y docker-ce docker-ce-cli containerd.io
    - docker compose config
