apiVersion: v1
kind: Service
metadata:
  name: localstack-service
  namespace: localstack
spec:
  selector:
    app: localstack
  ports:
  - name: localstack-gw
    protocol: TCP
    port: 4566
    targetPort: 4566
  - name: localstack-external-service
    protocol: TCP
    port: 4510  # Use a single port for the range
    targetPort: 4510  # Use a single port for the range

