apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack
        ports:
        - containerPort: 4566  # LocalStack Gateway
        envFrom:
          - configMapRef:
              name: localstack-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-config
  namespace: localstack
data:
  localstack-config.json: |
    {
      "services": "cloudwatch,dynamodb,ebs,ec2,iam,lambda,s3,sts",
      "port": 4566,
      "host": "localhost",
      "autoshutdown": "0",
      "env_vars": {
        "DEBUG": "1",
        "USE_SSL": "0",
        "SERVICES": "cloudwatch,dynamodb,ebs,ec2,iam,lambda,s3,sts",
        "AWS_DEFAULT_REGION": "us-east-1"
      }
    }

